services:
  - type: web
    name: trace360-backend
    env: docker
    region: ohio
    plan: free
    rootDir: backend
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./sih_anpr.db
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
 